name: museumLovers
description: A new Flutter project.

version: 1.0.3+5

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cached_network_image: ^3.3.1
  clock:
  collection:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
#  flutter_inappwebview: ^6.0.0
  freezed_annotation:
  http:
  json_annotation: ^4.4.0
  flutter_spinkit: ^5.1.0
  flutter_cache_manager: ^3.4.1
  permission_handler: ^11.3.1
  device_info_plus: ^9.1.2
#  image_gallery_saver: ^2.0.3
  fluttertoast: ^8.2.8
  url_launcher: ^6.0.20
  file: ^7.0.0

  google_mobile_ads: ^5.0.0
  app_tracking_transparency: ^2.0.2+1
  open_store: ^0.2.4
#  launch_review: ^3.0.1
  in_app_review: ^2.0.10
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.1
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/




